name: Build and deploy ASP.Net Core app to Azure Web App - app-lifeshare-davinci

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: List workspace files
        run: |
          echo "Listing all files in the workspace:"
          dir ${{ github.workspace }}

      - name: Build with dotnet
        run: dotnet build --configuration Release LifeShare.csproj

      - name: Create output directory
        run: |
          mkdir ${{ github.workspace }}/myapp
          echo "Created directory myapp."

      - name: Publish with dotnet
        run: |
          dotnet publish -c Release -o ${{ github.workspace }}/myapp LifeShare.csproj
          echo "Publish completed with exit code: $?"

      - name: List files in output directory
        run: |
          echo "Listing files in the output directory:"
          dir ${{ github.workspace }}/myapp

      - name: Check for errors
        run: |
          if (!(Test-Path -Path "${{ github.workspace }}/myapp")) {
            Write-Host "Directory myapp does not exist."
            exit 1
          }
          if (-Not (Get-ChildItem "${{ github.workspace }}/myapp")) {
            Write-Host "Directory myapp is empty."
            exit 1
          }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp/*

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: List downloaded files
        run: |
          echo "Listing files in the downloaded artifact:"
          dir ${{ github.workspace }}/myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D79AC7F09D7F48B5BBD5F9E2DCB2178F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BAFA376580D84598A17E4A24DF415BA1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_39885A5A29A64FCBAF994AA63E45736D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-lifeshare-davinci'
          slot-name: 'Production'
          package: ${{ github.workspace }}/myapp/*  # Atualizado para o caminho correto
